#!/bin/bash

if [[ $# != 3 ]]
then
   echo -e "\nUSAGE:"
   echo "lscp <server> <directory> <latest x files>"
   echo "Examples:"
   echo -e "\tlscp euler /user/bla/bla 5"
   echo -e "\tlscp user@euler /user/bla/bla 5"
   echo
   exit
fi

server=$1
dir=$2
lat=$3

echo "Copying latest $lat fukes from $server/$dir"
for i in $(ssh $server "ls -rt $dir | tail -n $lat")
do
  scp $server:$dir/$i .
done


