#!/usr/bin/env gawk -f

BEGIN {
  if (ARGC < 1) {
    printf("USAGE:\n")
    printf("regsort -v R=<regex> <file>\n")
    printf("\tE.g.: regsort -v R='^_(\\w+):.*' /etc/passwd\n")
  }
}
{
  if (match($0, R "$", a))
  {
    hash[a[1]NR]  = $0
  }
}
END {
  if (length(hash) == 0) {
    print "error: no match with regex"
    exit
  }
  n=asorti(hash, sorted)
  for (i = 1; i <= n; i++) {
    print hash[sorted[i]]
  }
}

